### ISSUE TITLE
The current pip package bombs the `site-packages` directory

### ISSUE THREAD

**Issue by guicho271828** [aibasel/pyperplan#10]
I observe the contents of `src/` are unpacked in the directory directly, rather than under the `pyperplan` directory

**Comment by maltehelmert** [comment]
I didn't know that a pip package for pyperplan exists. (Although that can also mean that someone told me and I forgot. ;-)) I'm not sure it is by us. @jendrikseipp, is it by you, or do you know more about it? Can you answer Masataro?

**Comment by jendrikseipp** [comment]
Yes, the pip package is by me. I actually fixed the issue you're reporting, Masataro, but didn't make a new release back then. Now that I look at it again, it still adds one extra file to the site-packages directory. I'll look into this and will make a release afterwards.

**Comment by jendrikseipp** [comment]
I just released version 2.0, which should fix this issue.

**Comment by guicho271828** [comment]
thanks!
