### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by tomsilver** [aibasel/pyperplan#6]
Thanks very much for this extremely useful package!

I wanted to flag a minor issue with `pip install pyperplan`. Installing the package in this way seems to add the contents of `src/` directly to the installation directory (e.g. `site-packages`). So for example, rather than having a `pyperplan` directory in my site package, I have  a `heuristics` directory, a `pddl` directory, etc. 

This causes conflicts if I am using pyperplan within a project that has files or directories with the names `heuristics`, `pddl`, etc.

**Comment by jendrikseipp** [comment]
Thanks for reporting this! We're looking into it.

**Comment by jendrikseipp** [comment]
I just pushed a fix. Could you please test this by doing `python3 -m pip install git+https://github.com/aibasel/pyperplan.git`?

**Comment by tomsilver** [comment]
@jendrikseipp thanks for the quick turnaround! I tested that command and it seems to have fixed the issue. Thanks again.

**Comment by jendrikseipp** [comment]
Nice, thanks for testing!
